<template>
<BContainer fluid class="my-5 mb-6 p-0 bg-white">
	<BContainer class="py-6 font-weight-bold text-dark">
		<h1>Power Market Terms and Conditions</h1>
		<div class="et_pb_module et_pb_text et_pb_text_0 et_pb_bg_layout_light  et_pb_text_align_left">
			<div class="et_pb_text_inner">
			<p><strong>Power Market Terms and Conditions</strong></p>
			<p>Revision Date: January 27, 2021</p>
			<p>&nbsp;</p>
			<p>Welcome to Power Market! These Terms and Conditions (these “Terms”) apply to your access to, and your use of our website located at&nbsp;<a href="https://pwrmarket.com/">https://pwrmarket.com/</a> (the “Site”), our mobile applications (collectively the “Apps” and each an “App”), and your participation in our Power Rewards loyalty program (the “Program”, together with the Site and Apps, collectively the “Services”), at Power Market convenience stores operated by H&amp;S Energy Products, LLC dba Power Market or Power Mart, or its subsidiaries, licensees and affiliated companies (collectively, “Power Market”, “we”, “us”, or “our”). These Terms are important, contain legal obligations and affect your legal rights, so please read them carefully. &nbsp;</p>
			<p>NOTE THAT SECTION 12 OF THESE TERMS CONTAINS A MANDATORY ARBITRATION PROVISION THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS AND LIMITS THE REMEDIES AVAILABLE TO YOU IN THE EVENT OF CERTAIN DISPUTES.</p>
			<p>BY CLICKING “I ACCEPT”, OR BY ACCESSING OR USING THE SERVICES, CREATING AN ACCOUNT, OR MAKING ANY PURCHASES, YOU AGREE TO THESE TERMS. YOU ALSO AGREE TO THE TERMS WHEN YOU MAKE A PURCHASE AS A GUEST. THESE TERMS ARE SUBJECT TO CHANGE AS DESCRIBED BELOW. IF YOU DO NOT AGREE TO THESE TERMS (OR ANY PORTION OF THESE TERMS), INCLUDING THE MANDATORY ARBITRATION PROVISION AND CLASS ACTION WAIVER IN SECTION 12 OF PART ONE, YOU MAY NOT ACCESS OR USE OUR SERVICES AND MUST IMMEDIATELY TERMINATE YOUR USE OF SERVICES.</p>
			<p><u>Part 1 – TERMS FOR ALL USERS</u></p>
			<ol>
			<li>Eligibility</li>
			</ol>
			<p>The Services are not targeted toward, marketed to, or intended for use by anyone under the age of 16. Power Market encourages parents to supervise their children’s digital activities and to consider using parental control tools available from online services and software manufacturers that help provide a child-friendly online environment. These tools can also keep children from disclosing online their name, address and other personal information without parental consent. Additional eligibility requirements apply to purchases made using the Services, and are set forth in Part Three.</p>
			<p>If you are using the Services on behalf of any person, you represent and warrant that you are authorized to accept these Terms on such person’s behalf and that such person agrees to be responsible to us if you or such person violates these Terms.</p>
			<ol start="2">
			<li>Accounts and Account Security</li>
			</ol>
			<p>In order to access and use certain areas or features of the Services, including to purchase any products made available through the Apps (the, “Products”), you will need to register for an account (an “Account”). You can create an Account as follows:</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp; *Download one of our Apps on a smartphone or other mobile device that is capable of downloading and running the App from the Apple App Store or Google Play Store (as applicable) and follow the prompts to create an Account. &nbsp;Power Market does not charge to download its Apps, but standard data rates may apply.</p>
			<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *Visit&nbsp;<a href="http://www.pwrmarket.com/rewards">www.pwrmarket.com/rewards</a> and follow the prompts to create an Account.</p>
			<p>By creating an Account, you agree to (a) provide accurate, current and complete Account information, (b) maintain and promptly update, as necessary, your Account information, (c) maintain the security of your Account credentials, (d) be responsible for the acts or omissions of any third party who has authority to access or use your Power Rewards Card or Account, including by use of the Services on your behalf, and (e) immediately notify us if you discover or otherwise suspect any security breaches related to your Account. We shall not be responsible for misdirected communications such as mail or e-mail or any consequences thereof.</p>
			<ol start="3">
			<li>Privacy Policy</li>
			</ol>
			<p>Power Market’s personal information practices, including the collection, use and/or disclosure of your personal information, are governed by Power Market’s privacy policy located at <a href="https://www.pwrmarket.com/privacy-policy">https://www.pwrmarket.com/privacy-policy</a>, which is hereby incorporated into these Terms by reference. We reserve the right to modify our privacy policy from time to time. While using the Services and from time to time, you may be asked whether or not you consent to and wish to receive marketing and other non-critical communications relating to the Services. If you agree and consent to receiving such communications from Power Market, you may opt-out of receiving such communications at any time as provided in our privacy policy.</p>
			<ol start="4">
			<li>Ownership, License &amp; Restrictions on Use</li>
			</ol>
			<p>4.1. The materials provided, contained in or made available for use in connection with the Services (collectively, the “Materials”) are protected by law, including, but not limited to United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The Services are controlled and operated by Power Market from its offices within the U.S. &nbsp;Power Market makes no representation that any of the Services or Materials are appropriate or available for use in other locations, and access to them from territories where their contents are illegal is prohibited. Those who choose and access any of the Services from other locations do so on their own initiative and are responsible for compliance with applicable local laws. See below for further copyright and trademark information.</p>
			<p>4.2. All rights, title and interest (including all copyrights, trademarks and other intellectual property rights) in the Services and the Materials belong to Power Market or the original creator of the material. Further, all names, designs, graphics, data, images, pictures, logos and icons on the Services and the Materials are proprietary information or proprietary marks of Power Market or the original creator of the material. The compilation of all content, including the look and feel of the Services (including the Materials), is the exclusive property of Power Market and is protected by U.S. copyright law, as applicable. Except as may be expressly provided herein, nothing contained in these Terms or elsewhere shall be construed as conferring any license or right, by implication, estoppels or otherwise, under copyright, trademark or other intellectual property rights, to any of the Materials.</p>
			<p>4.3. You are hereby granted a personal, non-exclusive, non-transferable, limited license to: (i) use the Apps on your mobile device for your personal non-commercial use only; and (ii) view the Sites, and to print insignificant portions of materials retrieved from the Sites provided (a) they are used only for informational, non-commercial purposes, and (b) you do not remove or obscure the copyright notice or other notices. You are not allowed to modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer or sell any information, products or services obtained directly from the Services (including the Materials). Further, you may not reproduce any part of the Services (including the Materials) and any such violation with respect to the Services will terminate the license(s) granted herein.</p>
			<p>4.4. You also may not, without the permission of Power Market, “mirror” any of the Materials on any other server. Any unauthorized use of any of the Materials may violate copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes, and subject you to civil and criminal prosecution.</p>
			<p>4.5. As between you and Power Market, all submissions, suggestions, ideas, artwork, or other information (the “Submission”) communicated to Power Market through the Services become the sole and exclusive property of Power Market. Power Market is not required to treat any Submissions as confidential, and will not incur any liability as a result of any similarities that may appear in future Power Market endeavors. Power Market will have exclusive ownership of all present and future existing rights, including all commercial rights, to the Submission of every kind and nature in perpetuity throughout the universe, without acknowledgment or compensation to you. You acknowledge that you are responsible for whatever material you submit, and that you, not Power Market, have full responsibility for the Submission, including its legality, reliability, appropriateness, novelty, and copyright. Power Market has the right but not the obligation to monitor and edit or remove any activity or content. Power Market takes no responsibility and assumes no liability for any content posted by you or any third party.</p>
			<p>4.6. The trademarks, service marks, and logos, including but not limited to Power Market’s name, logo, and all related names, logos, product and service names, service marks, designs, and slogans (the “Trademarks”) used and displayed on the Services (including the Materials) are registered and unregistered Trademarks of Power Market and others. Nothing on the Services should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed on the Services (including the Materials), without the written permission of the Trademark owner. Power Market aggressively enforces its intellectual property rights to the fullest extent of the law. Power Market’s Trademarks may not be used in any way, including in advertising or publicity pertaining to distribution of materials on the Services, without prior, written permission of Power Market. Power Market prohibits use of the Power Market and/or Power Mart logo as a “hot” link to any website, including Power Market sites, unless establishment of such a link is approved in advance by Power Market in writing.</p>
			<ol start="5">
			<li>User Conduct</li>
			</ol>
			<p>As a specific condition of your use of any of the Services, you explicitly agree not to (a) use any of the Services for any purpose that is unlawful or prohibited by these Terms; (b) intentionally submit or transmit inaccurate information through the Services; (c) impersonate or pretend to be anyone else while using the Services; (d) use the Services in any way that could damage, disable, overburden, or impair any of the Services, or interfere with anyone else’s use of any of the Services; (e) attempt to gain unauthorized access to Power Market computer systems or networks connected to Power Market, through hacking, password mining or any other means; (f) attempt to reverse engineer any portion of any of the Services or attempt to infringe the intellectual property rights of others in any way; (g) obtain or attempt to obtain any materials or information through any means not intentionally made available through any of the Services; (h) attempt to circumvent any content-filtering techniques we employ or attempt to access any feature or area of our Services that you are not authorized to access; (i) introduce any malicious or technologically harmful material into our Services; (j) develop or use any third-party applications that interact with our Services without our prior written consent, including any scripts designed to scrape or extract data from our Services; and (k) use our Services for any illegal or unauthorized purpose, or engage in, encourage or promote any activity that violates these Terms.</p>
			<ol start="6">
			<li>Third Party Content</li>
			</ol>
			<p>The Services may contain links to and from third party websites. Power Market has no control over the content or privacy policies of third party websites that you may link to from the Services or their advertisers. If you visit a linked website, be aware that the third party operating any such website may have access to any information you submit via that website. Power Market is not responsible for any third party’s failure to establish or abide by its or our privacy policy. We suggest always checking the privacy policy for each website that you visit prior to submitting any personal information. Links to third party websites do not imply endorsement of the websites by Power Market.</p>
			<ol start="7">
			<li>Fuel Prices</li>
			</ol>
			<p>You acknowledge and agree that any information pertaining to fuel prices is presented by Power Market on an “as is” basis, without any guarantee or representation by Power Market as to the accuracy of such information. Power Market disclaims, and you accept the information without, any warranties of any kind, either express or implied, as to the accuracy of the information. Although Power Market strives to provide you with timely, relevant and accurate information pertaining to fuel prices, the fuel prices displayed on the Site or the Apps are subject to change and may vary from those offered at your local Power Market location. Fuel prices displayed on the Site or the Apps are not and shall not be deemed an offer to you. Power Market does not guarantee, and you agree that you may not rely upon, the fuel prices displayed on the Site or in the Apps. The fuel price you ultimately pay will always be determined at the time and location of sale, as posted at the pump of the Power Market location from which you purchase fuel.</p>
			<ol start="8">
			<li>Revision Date, Modification; Changes</li>
			</ol>
			<p>These Terms are effective and were last updated as of the Revision Date at the beginning of these Terms. At any time, Power Market may revise these Terms at our sole discretion. If we make changes, we will post the amended Terms to our Services, and update the “Revision Date” date above. We may, but are not required to, notify you by sending an email notification to the address associated with your Account or providing notice through our Services. Revisions are effective and binding when posted on the Services. Any continued use of any of the Services following any revision means you agree to the revisions. Power Market expressly reserves the right to terminate or discontinue any of the Services at any time and for any reason, with or without notice to you.</p>
			<ol start="9">
			<li>Copyright Complaints</li>
			</ol>
			<p>We have a policy of limiting access to our Services and terminating the accounts of users who infringe the intellectual property rights of others. If you believe that anything on our Services infringes any copyright that you own or control, you may notify Power Market’s Designated Agent as follows:</p>
			<p>GKL Corporate/Search, Inc.</p>
			<p><strong>Entity Address:</strong></p>
			<p>ONE CAPITOL MALL STE 660<br> SACRAMENTO CA 95814</p>
			<p><strong>Entity Mailing Address:</strong></p>
			<p>PO BOX 1913<br> SACRAMENTO CA 95812</p>
			<p>Toll Free: (800) 446-5455</p>
			<p>Phone: (916) 442-7652</p>
			<p>Fax: (916) 442-1797</p>
			<p>Please see 17 U.S.C. §512(c)(3) for the requirements of a proper notification. Also, please note that if you knowingly misrepresent that any activity or material on our Services is infringing, you may be liable to Power Market for certain costs and damages.</p>
			<ol start="10">
			<li>Disclaimers</li>
			</ol>
			<p>EXCEPT AS MAY BE PROVIDED IN A WARRANTY BY THE MANUFACTURER OF A PRODUCT, THE SERVICES AND ALL CONTENT THEREIN ARE PROVIDED ON AN “AS AVAILABLE” AND “AS IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. WE DO NOT REPRESENT OR WARRANT THAT: (A) THE PROGRAM, SERVICES, PROMOTIONAL CONTESTS, AND MATERIALS ARE FREE OF ERRORS; (B) DEFECTS WILL BE CORRECTED; (C) THE SERVICES OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) INFORMATION COMMUNICATED THROUGH THE SERVICES ARE ACCURATE, COMPLETE, OR USEFUL.</p>
			<p>YOU ACKNOWLEDGE AND AGREE THAT YOUR ACCESS TO AND USE OF THE SERVICES OR ANY CONTENT THEREIN IS AT YOUR OWN RISK. ANY RELIANCE YOU PLACE ON INFORMATION PROVIDED TO YOU THROUGH THE SERVICES IS AT YOUR OWN RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR DEVICE OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH CONTENT, MATERIAL AND/OR DATA. WITHOUT LIMITING THE FOREGOING, POWER MARKET MAKES NO REPRESENTATION OR WARRANTY AS TO THE QUALITY, RELIABILITY, COMPLETENESS, ACCURACY, TIMELINESS, AVAILABILITY, SECURITY OR FUNCTIONALITY OF THE SERVICES OR ANY CONTENT THEREON. POWER MARKET WILL NOT BE LIABLE FOR ANY HARM TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE, OR LOSS OF DATA, THAT RESULTS FROM YOUR ACCESS TO OR USE OF THE SERVICES OR ANY CONTENT, OR FOR THE DELETION OF, OR THE FAILURE TO STORE. POWER MARKET MAKES NO WARRANTY THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS OR THAT DEFECTS IN THE SERVICES WILL BE CORRECTED. THE SERVICES MAY NOT BE CONTINUOUSLY AVAILABLE DUE TO MAINTENANCE OR REPAIRS OR DUE TO COMPUTER PROBLEMS OR CRASHES, DISRUPTION IN INTERNET SERVICE OR OTHER UNFORESEEN CIRCUMSTANCES. THE SERVICES AND ASSOCIATED CONTENT ARE INTENDED FOR USE AND DISPLAY ONLY WHERE ITS USE AND DISPLAY ARE PERMISSIBLE IN ACCORDANCE WITH APPLICABLE LAWS AND REGULATIONS. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED TERMS IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE DISCLAIMERS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
			<p>POWER MARKET DISCLAIMS ANY AND ALL RESPONSIBILITY FOR ANY LOSS, INJURY, CLAIM, LIABILITY, OR DAMAGE OF ANY KIND RESULTING FROM, ARISING OUT OF, OR IN ANY WAY RELATED TO (A) ANY ERRORS IN OR OMISSIONS ON OR FROM ANY OF THE SERVICES, PROMOTIONAL CONTESTS, AND CONTENT THEREIN, INCLUDING BUT NOT LIMITED TO TECHNICAL INACCURACIES AND TYPOGRAPHICAL ERRORS, (B) ANY THIRD PARTY WEBSITES OR CONTENT THEREIN DIRECTLY OR INDIRECTLY ACCESSED THROUGH LINKS IN THE SITES, THE APPS OR MATERIALS PROVIDED, MADE AVAILABLE IN CONNECTION WITH THE PROGRAM OR ANY PROMOTIONAL CONTESTS, INCLUDING BUT NOT LIMITED TO ANY ERRORS IN OR OMISSIONS CONTAINED THEREIN, (C) THE UNAVAILABILITY OF ANY OF THE SERVICES OR ANY PORTION THEREOF, (D) YOUR USE OF ANY OF THE SERVICES, OR PARTICIPATION IN ANY PROMOTIONAL CONTESTS, OR (E) YOUR USE OF ANY EQUIPMENT OR SOFTWARE IN CONNECTION WITH ANY OF THE SERVICES OR PROMOTIONAL CONTESTS.</p>
			<p>ANY DEALINGS WITH ANY THIRD PARTIES (INCLUDING ADVERTISERS AND/OR SPONSORS) APPEARING ON THE SITES, THE APPS OR MATERIALS PROVIDED OR MADE AVAILABLE IN CONNECTION WITH THE PROGRAM, PARTICIPATION IN ANY PROMOTIONS OR OFFERINGS (INCLUDING DELIVERY OF AND PAYMENT FOR GOODS AND SERVICES) AND ANY OTHER TERMS, CONDITIONS, WARRANTIES OR REPRESENTATIONS ASSOCIATED WITH SUCH ACTIVITIES ARE SOLELY BETWEEN YOU AND SUCH ADVERTISER OR OTHER THIRD PARTIES. WE ARE NOT RESPONSIBLE FOR EXAMINING OR EVALUATING, AND WE DO NOT WARRANT THE OFFERINGS OF, ANY OF THESE BUSINESSES OR INDIVIDUALS OR THE CONTENT OF THEIR WEBSITES. POWER MARKET DOES NOT ASSUME ANY RESPONSIBILITY OR LIABILITY FOR THE ACTIONS, PRODUCT, AND CONTENT OF ALL THESE AND ANY OTHER THIRD PARTIES. YOU SHOULD CAREFULLY REVIEW THEIR PRIVACY STATEMENTS AND OTHER CONDITIONS OF USE. POWER MARKET IS NOT RESPONSIBLE OR LIABLE TO ANY PARTY WHO PARTICIPATES IN ANY SUCH DEALINGS, PROMOTIONS OR OFFERINGS.</p>
			<p>WE ATTEMPT TO DISPLAY THE PRODUCTS AND OTHER MATERIALS AND INFORMATION YOU VIEW ON THE SERVICES, INCLUDING PRICING AND NUTRITIONAL INFORMATION, AS ACCURATELY AS POSSIBLE. HOWEVER, WE DO NOT GUARANTEE THE ACCURACY OF SUCH MATERIALS AND INFORMATION. IN THE EVENT OF AN ERROR ON OUR SERVICES, IN AN ORDER CONFIRMATION, IN PROCESSING OR DELIVERING AN ORDER OR OTHERWISE, WE RESERVE THE RIGHT TO CORRECT SUCH ERROR AND REVISE YOUR ORDER ACCORDINGLY (INCLUDING CHARGING THE CORRECT PRICE) OR TO CANCEL YOUR ORDER AND ISSUE YOU A REFUND. YOU FURTHER AGREE THAT THE PRODUCTS AND OTHER MATERIALS YOU RECEIVE IN YOUR ORDER MAY VARY FROM THE PRODUCTS AND MATERIALS DISPLAYED ON THE SERVICES DUE TO A NUMBER OF FACTORS, INCLUDING, WITHOUT LIMITATION, SYSTEM CAPABILITIES AND CONSTRAINTS OF YOUR COMPUTER, MANUFACTURING PROCESS OR SUPPLY ISSUES, THE AVAILABILITY AND VARIABILITY OF PRODUCTS, DISTINCT COOKING OR OTHER PREPARATION METHODS AND VARIABILITY OF COOKING EQUIPMENT AND APPLIANCES. THE SERVICES MAY CONTAIN INFORMATION ABOUT PRODUCTS THAT ARE NOT AVAILABLE IN EVERY LOCATION. A REFERENCE TO A PRODUCT ON THE SERVICES DOES NOT IMPLY OR GUARANTEE THAT IT IS OR WILL BE AVAILABLE IN YOUR LOCATION OR AT THE TIME OF YOUR ORDER.</p>
			<ol start="11">
			<li>Limitation of Liability</li>
			</ol>
			<p>IN NO EVENT WILL WE OR OUR DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, SUBSIDIARIES, PARENT COMPANIES, MEMBERS, SHAREHOLDERS, AGENTS OR OTHER REPRESENTATIVES BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, ARISING OUT OF OR RELATED TO THE SERVICES, OR THE ORDER, RECEIPT OR USE OF ANY PRODUCT. OUR TOTAL LIABILITY, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EVEN IF FORSEEABLE, WILL NOT EXCEED THE GREATER OF (I) THE TOTAL AMOUNT YOU SPENT ON PURCHASES FROM THE APPS IN THE MOST RECENT TWELVE-MONTH PERIOD, OR (II) IF YOU HAVE NOT PAID POWER MARKET, THE AMOUNT OF $100. THESE EXCLUSIONS AND LIMITATIONS OF LIABILITY WILL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW AND WILL SURVIVE CANCELLATION OR TERMINATION OF YOUR ACCOUNT. CERTAIN APPLICABLE LAWS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
			<ol start="12">
			<li>Dispute Resolution; Binding Arbitration</li>
			</ol>
			<p>PLEASE READ THE FOLLOWING SECTION CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES AND CLAIMS WITH POWER MARKET AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US. THIS INCLUDES A CLASS ACTION WAIVER.</p>
			<p>Access to and use of any of the Services and these Terms are governed by the laws of the State of California and the United States as applicable therein, without resort to conflict of law provisions. Power Market makes no representation that the contents of any of the Services are appropriate or available for use outside of the United States, and those who choose to access any of the Services from other locations are solely responsible for compliance with their local laws. Except for any disputes, claims, suits, actions, causes of action, demands, or proceedings (collectively, “Disputes”) arising out of or related to a violation of Section 5 or Disputes in which either party seeks to bring an individual action in small claims court or seeks injunctive or other equitable relief for the alleged unlawful use of intellectual property, including, without limitation, copyrights, trademarks, trade names, logos, trade secrets, or patents, you and Power Market agree to (a) waive your and Power Market’s respective rights to have any and all Disputes arising from or related to these Terms, or the Services resolved in a court, (b) waive your right to proceed in a class, collective, or consolidated capacity, and (c) waive your and Power Market’s respective rights to a jury trial. Your rights and Power Market’s rights during the arbitration process may be more limited than the rights you or Power Market would have in civil trial or appellate court. The Federal Arbitration Act and federal arbitration law apply to these Terms.</p>
			<p>Any Dispute arising out of or relating to any of the Services or these Terms will be settled by binding arbitration before JAMS, Inc. and in accordance with the JAMS Comprehensive Arbitration Rules and Procedures. The rules of JAMS and additional information about JAMS are available on the JAMS website. By agreeing to be bound by these Terms, you either (a) acknowledge and agree that you have read and understand the rules of JAMS, or (b) waive your opportunity to read the rules of JAMS and any claim that the rules of JAMS are unfair or should not apply for any reason.</p>
			<p>ANY SUCH DISPUTE SHALL BE ARBITRATED ON AN INDIVIDUAL BASIS, AND SHALL NOT BE CONSOLIDATED IN ANY ARBITRATION WITH ANY DISPUTE OF ANY OTHER PARTY.</p>
			<p>Each party shall be responsible for its costs incurred in such arbitration, but if you cannot afford to pay for the arbitration, you agree to provide us the option of paying the arbitrator before seeking to initiate any other form of dispute resolution, including litigation. The arbitration will be conducted in Orange County, California, and judgment on the arbitration award may be entered into by any court having jurisdiction thereof. The award of the arbitrator shall be final and binding upon the parties without appeal or review. You have the right to opt out of binding arbitration within thirty (30) days of the date you first accepted the terms of this Section 12 by writing to: Attn: Legal Department, Power Market, 2860 N. Santiago Blvd., CA 92867. In order to be effective, the opt-out notice must include your full name and clearly indicate your intent to opt out of binding arbitration. BY OPTING OUT OF BINDING ARBITRATION, YOU ARE AGREEING TO RESOLVE DISPUTES ON AN INDIVIDUAL BASIS IN A COURT LOCATED IN ORANGE COUNTY, CA. Notwithstanding the foregoing, Power Market may immediately seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect its rights or property (including intellectual property rights).</p>
			<p>THIS SECTION LIMITS CERTAIN RIGHTS, INCLUDING THE RIGHT TO MAINTAIN A COURT ACTION, THE RIGHT TO A JURY TRIAL, THE RIGHT TO PARTICIPATE IN ANY FORM OF CLASS OR REPRESENTATIVE CLAIM, THR RIGHT TO ENGAGE IN DISCOVERY EXCEPT AS PROVIDED IN JAMS RULES, AND THE RIGHT TO CERTAIN REMEDIES AND FORMS OF RELIEF. OTHER RIGHTS THAT YOU OR POWER MARKET WOULD HAVE IN COURT ALSO MAY NOT BE AVALIABLE IN ARBITRATION.</p>
			<ol start="13">
			<li>Governing Law and Venue</li>
			</ol>
			<p>These Terms, your access to and use of the Services, including your order of Products, and any claim or dispute you may bring against Power Market, its affiliates, subsidiaries, parent companies, members, shareholders, agents and assigns, shall be governed by and construed and enforced in accordance with the laws of the State of California, without regard to conflict of law rules or principles (whether of the State of California or any other jurisdiction) that would cause the application of the laws of any other jurisdiction. Any Dispute between the parties that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in the state or federal courts of the State of California and the United States, respectively, sitting in the State of California, County of Orange.</p>
			<ol start="14">
			<li>Termination</li>
			</ol>
			<p>Notwithstanding anything contained in these Terms, we reserve the right, without notice and in our sole discretion, to terminate your right to access or use the Services and to order, receive and use the Products, at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us, to the fullest extent permitted by applicable law.</p>
			<ol start="15">
			<li>Severability</li>
			</ol>
			<p>If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause or provision, or any other term, clause or provision of these Terms.</p>
			<ol start="16">
			<li>Survival</li>
			</ol>
			<p>The following sections will survive the expiration or termination of these Terms and the termination of your Power Market account: all defined terms and Sections 3, 4, 5, 10, 11, 12, 13, 14, 15, and 16 of Part One; and Sections 4.9 and 4.11 of Part Two; and Section 11 of Part Three.</p>
			<ol start="17">
			<li>Assignment</li>
			</ol>
			<p>If Power Market sells its assets to or is acquired by another company, or if it merges with another company, you, by using the Services, authorize Power Market to assign the information you provided to Power Market or that Power Market has collected while you use the Services.</p>
			<ol start="18">
			<li>Miscellaneous</li>
			</ol>
			<p>These Terms (including, for greater certainty, the additional items in Part Two and Part Three below) constitute the entire agreement between you and Power Market relating to your access to and use of the Services and your order, receipt and use of Products. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of Power Market. No waiver of any provision of these Terms will constitute a waiver of such provision in any prior, concurrent or subsequent circumstance, and Power Market’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Except as otherwise provided herein, these Terms are intended solely for the benefit of the parties and are not intended to confer third party beneficiary rights upon any other person or entity.</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>Part Two – <u>ADDITIONAL TERMS APPLICABLE TO THE Power Rewards LOYALTY PROGRAM</u></p>
			<p>These Loyalty Program Terms and Conditions (these “Program Terms”) are subject to, and made a part of the Terms, and apply to your access to, and your participation in the Program, which is operated by Power Market.</p>
			<p>These Program Terms do not alter in any way the terms or conditions of any other agreement you may have with us in respect of any products, services or otherwise.</p>
			<ol>
			<li>JOINING THE PROGRAM</li>
			</ol>
			<p>1.1. Eligibility</p>
			<p>There are no membership fees associated with the Program. The Program is open only to residents of the U.S. who are 16 years or older and are natural persons; no corporation, trust, partnership or other entity may participate in the Program. If you are between 13 and 18, you may join and participate in the Program only with the permission of a parent or guardian. Power Market encourages parents to supervise their children’s digital activities and to consider using parental control tools available from online services and software manufacturers that help provide a child-friendly online environment. These tools can also keep children from disclosing online their name, address and other personal information without parental consent.</p>
			<p>1.2. Power Rewards Cards/Other Methods</p>
			<p>You may also participate in the Program if you obtain a physical Power Rewards Card from one of our participating stores in California or join by other methods (e.g., join by SMS or in-store at the register). You will begin accumulating Points as soon as you scan your Power Rewards Card or your Account barcode (accessed through the Power Market App) at the time of purchase or providing the phone number linked to your Account at the time of purchase. If your Power Rewards Card, Account barcode or phone number are not linked to your Account (“Pre-Enrolled Participants”), You will be unable to redeem your accumulated Points and Punches unless and until your Power Rewards Card, Account barcode or phone number are linked to your Account. If you wish to link your Power Rewards Card, Account barcode, or phone number to an Account, you may create an Account as indicated above and link your Power Rewards Card, Account barcode or phone number to your newly created Account or, if you already have an existing Account, link your Power Rewards Card, Account barcode or phone number to your existing Account under your Account page in the Power Market App or on the Site.</p>
			<ol start="2">
			<li>PROGRAM DESCRIPTION</li>
			</ol>
			<p>2.1. Accumulating Points</p>
			<p>Except for purchases of certain Excluded Items identified below, the Program enables you to accumulate promotional Power Points (“Points”) on all other purchases (“Qualifying Purchases”) and to convert your Points into My Rewards redeemable for certain eligible items at participating Power Market stores in California. You will accumulate one (1) Point for each One-Dollar (USD$1.00) you spend on Qualifying Purchases in accordance with this section. Taxes and fees are excluded and ineligible for Point accrual. Points may take longer than 24 hours from the time of the last Qualifying Purchase to show up in your Account. We reserve the right, in our sole discretion, to limit the number of transactions per day for which Points may be awarded as well as the number of Points per day that a Program member may earn.</p>
			<p>In order to accumulate Points for Qualifying Purchases, you must identify yourself as a Power Rewards member at the time of purchase (by presenting and scanning your Power Rewards Card, your Account barcode (accessed through the Power Market App at the time of purchase or providing the phone number linked to your Account at the time of purchase) in order to record and qualify your purchase. Points and My Rewards are promotional only. Points and My Rewards have no value, may not be redeemed for cash, and are not transferable to any other individual or entity. Points will not be accumulated on the portion of any transaction that was paid for or credited by using or redeeming My Rewards or other discounts or promotional codes. Points will not be accumulated on purchases of the following products/services: fuel, age-restricted items (such as cigarettes, tobacco, lottery tickets and alcohol), financial services, prepaid card products, money orders, gift cards, phone cards, stamps, Post Office stamps and merchandise, event tickets, bus tickets and passes, charitable donations, gift with purchases or as may be excluded in a particular promotions, and any other items specified as exclusions from time to time (collectively, the “Excluded Items”). We reserve the right to add or delete products and services eligible for redemption or Point collection at any time, at our sole discretion, without notice.</p>
			<p>If you cancel or return a Qualifying Purchase for which you have collected Points, Power Market may deduct the Points that you were awarded for that purchase.</p>
			<p>2.2 Punch Programs</p>
			<p>From time-to-time, Power Market may offer “punch” programs to earn free products in all or certain stores. Details of any such program will be set forth in the rules of such program and/or communicated to you via point-of-purchase display, email, or in-app messaging, and may enable you to get one free product (as we may specify, the “Punch Reward”) for a number of such products that you buy at participating Power Market stores in California when you present and scan your Power Rewards Card or your Account barcode (accessed through the Power Market App) at the time of purchase or provide the phone number linked to your Account at the time of purchase in order to record and qualify your purchase (each represented as punches on the digital punch card in your Account, if you have an Account and have properly linked and recorded your purchase to your Account, collectively, “Punches”). However, earning Punches for purchases made from the Power Market NOW App are addressed differently, in accordance with Part Three below. We reserve the right, in our sole discretion, to limit the number of transactions per day for which Punches may be awarded. Power Market may, in its sole discretion, modify or discontinue any Punch program at any time without notice to you.</p>
			<p>2.3. Limitations on Punches</p>
			<p>Punches are promotional only. Punches have no value, may not be redeemed for cash, and are not transferable to any other individual or entity. Punches will not be accumulated on the portion of any transaction that was paid for or credited by using or redeeming Points, Punches, Power Rewards, other discounts or promotional codes.</p>
			<p>If you cancel a purchase or return a product for which you have collected Punch(es), Power Market may deduct the Punch(es) that you were awarded for that purchase or product.</p>
			<ol start="3">
			<li>REDEMPTIONS</li>
			</ol>
			<p>3.1 Redeeming Point Rewards and Punches</p>
			<p>You may redeem your accumulated Points for rewards (“Point Rewards”) and products (“Reward Products”). &nbsp;Point Rewards and Reward Products are subject to availability. You may only redeem Points for Point Rewards and Reward Products at participating Power Market stores in California. Power Market reserves the right to change or discontinue any food or drink products, and to change the amount or kind of Points necessary to redeem Points for Point Rewards or Reward Products at any time. Once Point Rewards or Reward Products have been redeemed, they cannot be credited back to your Account.</p>
			<p>In accordance with applicable tax laws, applicable taxes are calculated and payable by any Program member on the full amount of the purchase price before any reduction for redeemed Point Rewards or Reward Products.</p>
			<p>If you have an Account and have properly recorded Points or Punches to your Account or converted your Points to Point Rewards or are eligible to receive a free Reward Product, there may be periods of time where your accumulated Points, Point Rewards, Punches, or Reward Products do not appear in your Account. Rest assured, such Points, Point Rewards, Punches, or Reward Products are still linked to your Account, and are available for conversion or redemption in accordance with these Program Terms once availability resumes.</p>
			<p>3.2. Obtain and Redeem Point Rewards with your Points</p>
			<p>You may obtain Point Rewards with your Points. Points may be redeemed for certain items or for discounts on eligible items at the time of purchase at participating Power Market stores in California. We reserve the right to add or delete products and services eligible for redemption using Point Rewards at any time, at our sole discretion, without notice. We reserve the right to add or remove the availability of any dollar-denominated discount eligible for redemption using Points at any time, at our sole discretion, without notice. For further details of items that you can obtain with your Point Rewards, please log into your Account and follow the prompts to view the list of available items. Points cannot be redeemed on purchases of the following products/services: age-restricted items (such as cigarettes, tobacco, lottery tickets and alcohol), financial services, prepaid card products, money orders, gift cards, phone cards, stamps, Post Office stamps and merchandise, event tickets, bus tickets and passes, charitable donations, gift with purchases or as may be excluded in a particular promotions, and any other items specified as exclusions from time to time (collectively, the “Excluded Items”). In order to obtain Point Rewards with your Points, follow the prompts in your Account to convert your Points into redeemable items or in-store at the register to convert your Points into discounts (each will be represented as a redeemable item in the “digital wallet” in your Account, Point Rewards, and together with Punch Rewards, collectively, “My Rewards”). When obtaining a Punch Reward with your Points, you must have enough Points to obtain the applicable Point Reward. POINT REWARDS MAY NOT BE USED TO OBTAIN EXCLUDED ITEMS. Once the Points you have accumulated are converted into Point Rewards, those Points will immediately be deducted from your Account, and cannot be credited back to your Account or converted into another Point Reward. You must use the same Account when converting Points to Point Rewards and cannot combine and convert Points accumulated in separate Accounts into Point Rewards.</p>
			<p>3.3. Redeeming Punches</p>
			<p>You may only redeem Punches for a free Reward Product at participating Power Market stores in California. You will qualify for one free Reward Product based upon the applicable number of Punches (as we may specify) you have properly recorded to your Account and/or Power Rewards Card. At that time of redemption, the Punches will immediately be deducted from your Account and/or Power Rewards Card and cannot be credited back to your Account and/or Power Rewards Card or converted into another Reward Product. &nbsp;If you have created an Account and have properly linked and recorded the applicable number of Punches (as we may specify) to your Account, your Account will be updated so that you can scan to receive your free Reward Product. You must use the same Account when redeeming Punches and cannot combine Punches accumulated in separate Accounts to redeem your free Reward Product. At this time, Punches may not be redeemed in the Power Market NOW App.</p>
			<ol start="4">
			<li>MISCELLANEOUS</li>
			</ol>
			<p>4.1. Prohibited Conduct</p>
			<p>In addition to the restrictions you agreed to in Power Market’s Terms, you agree that any fraud, attempted fraud, suspected fraud, or abuse of the Program or these Program Terms is expressly prohibited and engaging in any of these activities will be grounds for immediate termination and disqualification from the Program and may lead to the forfeiture of all earned Points and Punches.</p>
			<p>4.2. Expiration</p>
			<p>POINTS AND PUNCHES WHICH HAVE ACCUMULATED BY A PRE-ENROLLED PARTICIPANT WILL EXPIRE SIXTY (60) DAYS AFTER THE POINT OR PUNCH IS EARNED UNLESS THE POWER REWARDS CARD OR PHONE NUMBER IS LINKED TO AN ACCOUNT BEFORE THE EXPIRATION OF SUCH SIXTY (60) DAY PERIOD. UNLESS OTHERWISE PROHIBITED BY LAW, ALL ACCUMULATED POINTS AND PUNCHES IN YOUR ACCOUNT WILL AUTOMATICALLY EXPIRE IF FOR NINETY (90) CONSECUTIVE DAYS YOU HAVE NOT EITHER (I) USED YOUR ACCOUNT TO PROPERLY EARN AND RECORD POINTS OR OTHERWISE HAD PROMOTIONAL POINTS AWARDED TO YOUR ACCOUNT (WHICH WE HAVE NO OBLIGATION TO AWARD), (II) PROPERLY CONVERTED POINTS IN YOUR ACCOUNT TO A MY REWARD, (III) USED YOUR ACCOUNT TO PROPERLY EARN AND RECORD PUNCHES, OR (IV) PROPERLY REDEEMED A MY REWARD IN YOUR ACCOUNT.</p>
			<p>IN THE EVENT THAT YOU HAVE MY REWARDS (INCLUDING POINT REWARDS AND PUNCH REWARDS) IN YOUR ACCOUNT, YOU HAVE THIRTY (30) DAYS FROM THE DATE OF CONVERSION OR EARNING TO REDEEM THOSE MY REWARDS, OTHERWISE THEY WILL EXPIRE.</p>
			<p>4.3. Discrepancies</p>
			<p>If you believe there is a discrepancy with the number of accumulated Points or Punches or any My Rewards in your Account, you must notify us at the contact particulars below within sixty (60) days of the discrepancy date or it will be deemed correct.</p>
			<p>4.4. Lost Power Rewards Card or Compromised Accounts</p>
			<p>If your Power Rewards Card has been lost or stolen, you should notify us immediately at the contact particulars below. When Power Market is made aware of a lost or stolen Power Rewards Card, it will flag the card as lost or stolen and the lost or stolen card will be rendered inactive. A replacement Power Rewards Card can be obtained at a Power Market participating location. If the lost or stolen Power Rewards Card is linked to your Account, your registration profile and the accumulated, unredeemed Points, Punches and My Rewards at the time such card is rendered inactive will remain intact. If the lost or stolen Power Rewards Card is not linked to your Account, your accumulated Points and Punches at the time such card is lost or stolen will also be lost and unrecoverable. We are not responsible for any Points, Punches or My Rewards used by a third party using a lost or stolen Power Rewards Card, and if the lost or stolen Power Rewards Card is not linked to your Account, we are not responsible for the use or loss of any of your Points and Punches. Should the security of your Account be compromised, including in the event your mobile phone or other electronic device capable of accessing your Account is lost, stolen or compromised, you should re-set your Account password immediately. We are not responsible for any Points, Punches or My Rewards used by a third party accessing your Account.</p>
			<p>&nbsp;</p>
			<p>4.5. Member Communications</p>
			<p>By creating an Account, you consent to receive electronic communications from Power Market (e.g., via email or by posting notices on the Power Market App or Site). These communications may include notices about promotional events, your Account (e.g., payment authorizations, password changes, security concerns and other transactional information) and are part of your relationship with us. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including, but not limited to, that such communications be in writing.</p>
			<p>4.6. Promotional Events</p>
			<p>From time to time, Power Market may offer promotional events. By providing your email address, you consent to be automatically entered into our promotional events. As part of your consent, you authorize Power Market to communicate with you electronically (via email) about such promotional events, and to send you the promotional events’ descriptions and official terms and conditions that apply to such promotional events. THE WINNER OF ANY PROMOTIONAL EVENTS MAY BE REQUIRED TO SATISFY ADDITIONAL CRITERIA IN ACCORDANCE WITH APPLICABLE TERMS AND CONDITIONS, INCLUDING COMPLETING AND RETURNING A WAIVER AFFIDAVIT AND LIABILITY/PUBLICITY RELEASE IN ORDER TO RECEIVE THE APPLICABLE PRIZE. In the event you are a winner, we may share your name and contact information with a third-party promotional company in order to facilitate the fulfillment of your prize and you consent to such sharing. In the event that you wish to withdraw your consent to such sharing, or desire to opt out of marketing and promotional communications and events, you can do so by (i) following the instructions in the email or other communication, (ii) following the opt out instructions in the terms and conditions, or (iii) closing your Account.</p>
			<p>4.7. Program Cancellation or Change</p>
			<p>Power Market reserves the right to change, modify, or cancel the Program and these Program Terms at any time and in our sole discretion. We specifically reserve the right to amend or alter the Program, any Program benefit or award/reward or these Program Terms with or without notice. If we cancel or make changes to the Program and/or these Program Terms, we may provide notice of such changes, such as by sending an email notification, providing notice through the Services or updating the “Revision Date” date at the beginning of these Program Terms. By continuing to access or participate in the Program, you confirm your acceptance of the revised Program Terms and all of the terms incorporated therein by reference. We encourage you to review these Program Terms frequently to ensure that you understand the terms and conditions that apply when you access or participate in the Program. If you do not agree to the revised Program Terms, you may not access or participate in the Program. If Power Market cancels the Program, it will provide at least sixty (60) days’ advance notice of the cancellation through a notification in the Power Market App and at <a href="http://www.pwrmarket.com/powerrewards">www.pwrmarket.com/powerrewards</a>. You are responsible for checking the Power Market App and the Power Rewards section of the Site for updates about the Program. If Power Market cancels the Program, all of your Points, Punches and My Rewards will automatically and immediately expire upon the effective date of cancellation. If no Points or Punches are recorded in your Account for 366 consecutive days, you become bankrupt, commit fraud, misrepresent any information, violate any Terms, abuse your Program privileges or act in any other way to the detriment of us, our partners, our suppliers or the Program, we may, without affecting our other rights, disclose such information requested by proper authorities, terminate your enrollment and/or cancel your Points, Punches or My Rewards. If any Points, Punches or My Rewards are cancelled for any reason, they become void without compensation. Power Market reserves the right, at its sole discretion, to cancel or suspend the Program without notice should a virus, bug or any other cause beyond the reasonable control of Power Market corrupt the security or proper administration of the Program.</p>
			<p>Any fraudulent, deceptive, unauthorized, or otherwise unlawful participation in the Program or use of the Power Rewards Card, the Services, or your Account is strictly prohibited, and may result in immediate termination or disqualification from the Program and cancellation of your Account. The Power Rewards Card is the property of Power Market and may be revoked at any time by Power Market in its sole discretion. Any unauthorized reproduction of the Power Rewards Card may lead to legal prosecution and cancellation of your Account and the expiration of all accumulated Points, Punches and My Rewards.</p>
			<p>IF YOUR ACCOUNT IS CANCELLED, ANY REMAINING POINTS, PUNCHES AND MY REWARDS WILL EXPIRE.</p>
			<p>4.8. Your Choices</p>
			<p>As part of the Program, you will have access to your Account on the Power Market App or Site, which will provide information about your Account, including your accumulated Points, Punches and My Rewards, and your Account preferences. From the Account, you can update your profile information and can manage Account settings, such as opt-outs.</p>
			<p>4.9. Disclaimers</p>
			<p>IN ADDITION TO OTHER LIMITATIONS AND EXCLUSIONS IN POWER MARKET’S TERMS LOCATED AT <a href="http://www.pwrmarket.com/terms-and-conditions">www.pwrmarket.com/terms-and-conditions</a>, IN NO EVENT WILL WE OR OUR DIRECTORS, MEMBERS, SHAREHOLDERS, AFFILIATES, PARENT COMPANIES, OFFICERS, EMPLOYEES, AGENTS OR OTHER REPRESENTATIVES BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, ARISING OUT OF OR RELATED TO THE PROGRAM, POWER REWARDS CARD, OR ANY PROMOTIONAL EVENTS. OUR TOTAL LIABILITY TO YOU WITH RESPECT TO THE PROGRAM, PROMOTIONAL CONTESTS, AND CONTENT THEREIN, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WILL NOT EXCEED THE GREATER OF (I) THE TOTAL AMOUNT YOU SPENT ON SCANNED QUALIFYING PURCHASES IN THE MOST RECENT TWELVE-MONTH PERIOD, OR (II) IF YOU HAVE NOT PAID POWER MARKET, THE AMOUNT OF USD$100. THESE EXCLUSIONS AND LIMITATIONS OF LIABILITY WILL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW AND WILL SURVIVE CANCELLATION OR TERMINATION OF YOUR ACCOUNT. CERTAIN APPLICABLE LAWS MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
			<p>4.10. Other</p>
			<p>The Program is void where prohibited. Your accumulated Points and Punches and any My Rewards available for redemption are promotional in nature, have no cash value, and cannot be sold, copied, shared, or transferred. No substitutions, assignments, or transfers of any Qualifying Purchases will be permitted. Power Market’s decisions in connection with this Program are final and binding. Power Market will not be responsible for any Internet, mobile device, computer, or communications-related failures or any events beyond the reasonable control of Power Market. Any provision of these Program Terms deemed unenforceable will be enforced to the maximum extent permissible, and the remainder of these Program Terms will remain in effect.</p>
			<p>We reserve the right to impose volume limitations on some items, and to offer additional and/or different benefits to some members based on geographic location, participation in the Program, or other criteria determined by us.</p>
			<p>Your Account, your Power Rewards Card, and accumulated Points, Punches and My Rewards are personal to you, and may not be sold, transferred or assigned to, or shared with family, friends, or others, and may not be used for any commercial purpose.</p>
			<p>The Program is subject to Power Market’s Privacy Policy located at <a href="https://www.pwrmarket.com/privacy-policy">https://www.pwrmarket.com/privacy-policy</a>.</p>
			<p>If you have any questions, comments or concerns about the Program or these Program Terms, you may contact us at the following address:</p>
			<p>H&amp;S Energy Products, LLC dba Power Market</p>
			<p>Attn: Member Support<br> 2860 N. Santiago Blvd., Orange, CA 92867<br> membersupport@pwrmarket.com</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			</div>
		</div>
	</BContainer>
</BContainer>
</template>