module.exports = {
	featured: [
		{
			title: 'Pizza 7" + Fountain Drink 32oz',
			price: '$4.99',
			priceTag: '+ tax',
			img: 'https://images2.imgbox.com/7d/04/iUIXhrj2_o.png',
			size: '4',
		},
		{
			title: 'Combo Deli Family Deal: "Chicken 8pc & Pepsi 2L"',
			price: '$9.99',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/d9/ee/xTEa4zoE_o.png',
			size: '4',
		},
		{
			title: 'Fountain Drink (Any Size)',
			price: '$0.99',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/43/3c/DUVfYXUO_o.png',
			size: '4',
		},
	],

	main: [
		{
			title: 'Aquafina & Dasani 1L',
			price: '2 for $2.49',
			priceTag: '+ crv',
			img: 'https://images2.imgbox.com/64/70/dtcay3H8_o.png',
			size: '4',
		},
		{
			title: 'Rockstar 16oz',
			price: '2 for $3.49',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/19/6b/vyu5xmOu_o.png',
			size: '4',
		},
		{
			title: 'PM Water 1L',
			price: '2 for $2.99',
			priceTag: '+ crv',
			img: 'https://images2.imgbox.com/cd/2b/aXQn529g_o.png',
			size: '4',
		},
		{
			title: 'Nestle 24 Pack',
			price: '$4.99',
			priceTag: '+ crv',
			img: 'https://images2.imgbox.com/4b/8c/Rsy7RdJv_o.png',
			size: '4',
		},
		{
			title: 'Pepsi 12 Pack',
			price: '2/$9.49',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/ec/0b/wxz63Xnx_o.png',
			size: '4',
		},
		{
			title: 'Bang, Monster & Reign 16oz',
			price: '2 for $4.49 or 3 for $5.99',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/1e/d9/TisDOatY_o.png',
			size: '4',
		},
		{
			title: 'Candy Bars',
			price: 'King Size 2/$3.99 & Regular Size 2/$2.99',
			priceTag: '',
			img: 'https://images2.imgbox.com/85/2a/b1VNHJko_o.png',
			size: '4',
		},
		{
			title: 'Papa Sal\'s Beef Jerky 10oz',
			price: '$15.99 each',
			priceTag: '',
			img: 'https://images2.imgbox.com/68/76/pZjrhJPN_o.png',
			size: '4',
		},
		{
			title: 'Papa Sal\'s Snacks 4-7oz',
			price: '$3.99 each',
			priceTag: '',
			img: 'https://images2.imgbox.com/ec/7b/gEe1pCnh_o.png',
			size: '4',
		},
		{
			title: 'Red Bull 12oz',
			price: '2 for $5.33',
			priceTag: '+ crv + tax',
			img: 'https://images2.imgbox.com/03/81/JLuWUDA2_o.png',
			size: '4',
		},
	],
}